<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/MasterPage/MainLayout.Master" CodeBehind="AdminDeleteUser.aspx.cs" Inherits="FoodApp.AdminDeleteUser" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>



<asp:Content ID="Content5" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <div class="row">
        <div class="col l12 m12 s12">
    <asp:GridView ID="UserDataTable" runat="server" Width="100%" AutoGenerateDeleteButton="true" OnRowDeleting="UserDataTable_RowDeleting"></asp:GridView><br />
            </div>
        </div>
        </div>

</asp:Content>
