<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/MasterPage/MPUserManagement.master" CodeBehind="AdminDeleteUser.aspx.cs" Inherits="FoodApp.AdminDeleteUser" %>




<asp:Content ID="Content5" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <div class="row">
            <div class="section"></div>
        <div class="col l12 m12 s12">
            <div class="section">
                <h4 class="center">DELETE USER</h4>
            </div>
            <div class="section center">
    <asp:GridView ID="UserDataTable" runat="server" Width="100%" AutoGenerateDeleteButton="true" OnRowDeleting="UserDataTable_RowDeleting"></asp:GridView><br />
            </div>
            </div>
        </div>
        </div>

</asp:Content>
