<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AdminManageOwnRecipe.aspx.cs" Inherits="FoodApp.AdminManageOwnRecipe" MasterPageFile ="~/MasterPage/MPRecipeManagement.master" %> 
 <asp:Content ContentPlaceHolderID="ContentPlaceHolder1" runat ="server">
     <div class="container" style="min-height:57vh"><br />
        <div class="section">
             <h3 class="center grey-text">MANAGE MY RECIPES</h3>
         </div>
         <div class="section">
            <asp:GridView ID="AdminRecipeTable" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" AutoGenerateSelectButton="true" OnSelectedIndexChanging="AdminRecipeTable_OnSelectedIndexChanging" OnRowDeleting="AdminRecipeTable_RowDeleting" OnSelectedIndexChanged="AdminRecipeTable_SelectedIndexChanged" Width="100%" CssClass="striped highlight">
                <Columns>
                    <asp:BoundField DataField="RecipeID" HeaderText="Recipe ID" ReadOnly="true" />
                    <asp:TemplateField HeaderText="Name">
                        <ItemTemplate>
                            <asp:Label ID="lblRecipeName" runat="server" Text='<%# Bind("Name") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div><br />
    </div>
 </asp:Content>




  
       
