<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AdminManageOwnRecipe.aspx.cs" Inherits="FoodApp.AdminManageOwnRecipe" MasterPageFile ="~/MasterPage/MPRecipeManagement.master" %> 




 <asp:Content ContentPlaceHolderID="ContentPlaceHolder1" runat ="server">
     <div class="container" style="min-height:57vh">
     <br />
         <div class="section">
             <h4 class="center">MANAGE OWN RECIPES</h4>
         </div>
         <div class="section">
     <asp:GridView ID="AdminRecipeTable" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" AutoGenerateSelectButton="true" OnSelectedIndexChanging="AdminRecipeTable_OnSelectedIndexChanging" OnRowDeleting="AdminRecipeTable_RowDeleting" OnSelectedIndexChanged="AdminRecipeTable_SelectedIndexChanged" >
            <Columns>
                
                <asp:BoundField DataField="RecipeID" HeaderText="Recipe ID" ReadOnly="true" />

                <asp:TemplateField HeaderText="Name">
                    <ItemTemplate>
                        <asp:Label ID="lblRecipeName" runat="server" Text='<%# Bind("Name") %>'></asp:Label>
                    </ItemTemplate>
                    
                </asp:TemplateField>

                <asp:TemplateField HeaderText="MealType">
                    <ItemTemplate>
                        <asp:Label ID="lblMealType" runat="server" Text='<%# Bind("MealTypeID") %>'></asp:Label>
                    </ItemTemplate>
                    
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Portion">
                    <ItemTemplate>
                        <asp:Label ID="lblPortion" runat="server" Text='<%# Bind("Portion") %>'></asp:Label>
                    </ItemTemplate>
                    
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Cooking Time">
                    <ItemTemplate>
                        <asp:Label ID="lblCookingTime" runat="server" Text='<%# Bind("CookingTime") %>'></asp:Label>
                    </ItemTemplate>
                    
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Description">
                    <ItemTemplate>
                        <asp:Label ID="lblDescription" runat="server" Text='<%# Bind("Description") %>'></asp:Label>
                    </ItemTemplate>
                    
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
             </div>
         <br />
         </div>
 </asp:Content>




  
       
