<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AdminManageOwnRecipe.aspx.cs" Inherits="FoodApp.AdminManageOwnRecipe" %> 
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Manage Recipe</title>
</head>
<body>
    <form id="form1" runat="server">
     <asp:GridView ID="AdminRecipeTable" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowDataBound="AdminRecipeTable_RowDataBound" OnRowDeleting="AdminRecipeTable_RowDeleting" OnRowEditing="AdminRecipeTable_RowEditing"  OnRowUpdating="AdminRecipeTable_RowUpdating" OnRowCancelingEdit="AdminRecipeTable_RowCancelingEdit">
            <Columns>

                <asp:BoundField DataField="RecipeID" HeaderText="Recipe ID" ReadOnly="true" />

                <asp:TemplateField HeaderText="Name">
                    <ItemTemplate>
                        <asp:Label ID="lblRecipeName" runat="server" Text='<%# Bind("Name") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="EditRecipeName" runat="server" ></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="MealType">
                    <ItemTemplate>
                        <asp:Label ID="lblMealType" runat="server" Text='<%# Bind("MealTypeID") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:DropDownList ID="EditMealType" runat="server" ></asp:DropDownList>
                    </EditItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Portion">
                    <ItemTemplate>
                        <asp:Label ID="lblPortion" runat="server" Text='<%# Bind("Portion") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:DropDownList ID="EditPortion" runat="server" ></asp:DropDownList>
                    </EditItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Cooking Time">
                    <ItemTemplate>
                        <asp:Label ID="lblCookingTime" runat="server" Text='<%# Bind("CookingTime") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:DropDownList ID="EditCookingTime" runat="server" ></asp:DropDownList>
                    </EditItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Description">
                    <ItemTemplate>
                        <asp:Label ID="lblDescription" runat="server" Text='<%# Bind("Description") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="EditDescription" runat="server" MaxLength="99999" Rows="5"></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
    </form>
    </body>
    </html>
  
       
