<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AdminAddEditDeleteFoodItem.aspx.cs" Inherits="FoodApp.AdminAddEditDeleteFoodItem" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Add / Edit / Delete Food Item</title>
</head>
<body>
    <form id="form1" runat="server">
        <asp:GridView ID="FoodTable" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowDeleting="FoodTable_RowDeleting" OnRowEditing="FoodTable_RowEditing" OnRowUpdating="FoodTable_RowUpdating" OnRowCancelingEdit="FoodTable_RowCancelingEdit">
            <Columns>
                <asp:BoundField DataField="FoodItemID" HeaderText="Food Item ID" ReadOnly="true" />
                <asp:TemplateField HeaderText="Food Name">
                    <ItemTemplate>
                        <asp:Label ID="lblFoodName" runat="server" Text='<%# Bind("Name") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtFoodName" runat="server" Text='<%# Bind("Name") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Unit Type">
                    <ItemTemplate>
                        <asp:Label ID="lblUnitType" runat="server" Text='<%# Bind("UnitType") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtUnitType" runat="server" Text='<%# Bind("UnitType") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="FoodTypeID" HeaderText="Food Type ID" ReadOnly="true" />
            </Columns>
        </asp:GridView><br />
        <br />
        <asp:ValidationSummary ID="ValidationSummary1" runat="server" />
        Food Name:<br />
        <asp:TextBox ID="txtFoodName" runat="server"></asp:TextBox><br />
        Food Category:<br />
        <asp:DropDownList ID="ddlFoodType" runat="server"></asp:DropDownList><br />
        Unit Type:<br />
        <asp:DropDownList ID="ddlUnitType" runat="server"></asp:DropDownList><br />
        <br />
        <asp:Button ID="btnAddFoodItem" runat="server" Text="Add Food Item" OnClick="btnAddFoodItem_Click" />
        <asp:RequiredFieldValidator ID="RequiredFoodName" runat="server" ErrorMessage="Food Name is requird" ForeColor="Red" ControlToValidate="txtFoodName" Display="None"></asp:RequiredFieldValidator>
    </form>
</body>
</html>
