<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/MasterPage/DashBoard.Master" CodeBehind="SearchIngredient.aspx.cs" Inherits="FoodApp.SearchIngredient" %>

    <asp:Content ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
        <div class="row">
       <div class="col-md-12 col-lg-12">   
        Search by name<br />
        <asp:TextBox ID="txtBoxSearchName" runat="server"></asp:TextBox> in Category: 
        <asp:DropDownList ID="ddlCategory" runat="server">
        </asp:DropDownList>
        <asp:Button ID="btnSearchIngredient" runat="server" OnClick="btnSearchIngredient_Click" Text="Search" />
        <br />
        <br />
        </div>
        <div class="col-md-12 col-lg-12">  
        <asp:GridView ID="FoodTable" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowDataBound="FoodTable_RowDataBound" OnRowDeleting="FoodTable_RowDeleting" OnRowEditing="FoodTable_RowEditing" OnRowUpdating="FoodTable_RowUpdating" OnRowCancelingEdit="FoodTable_RowCancelingEdit" Width="100%">
            <Columns>
                <asp:BoundField DataField="FoodItemID" HeaderText="Food Item ID" ReadOnly="true" />
                <asp:TemplateField HeaderText="Food Name">
                    <ItemTemplate>
                        <asp:Label ID="lblFoodName" runat="server" Text='<%# Bind("Name") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtUpdateFoodName" runat="server" Text='<%# Bind("Name") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Unit Type">
                    <ItemTemplate>
                        <asp:Label ID="lblUnitType" runat="server" Text='<%# Bind("UnitType") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddlUpdateUnitType" runat="server"></asp:DropDownList>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Food Type">
                    <ItemTemplate>
                        <asp:Label ID="lblFoodType" runat="server" Text='<%# Bind("FoodTypeID") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddlUpdateFoodType" runat="server"></asp:DropDownList>
                    </EditItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
        </div>
    </div>
    </asp:Content> 
   

